CREATE TABLE DiseaseSpecialization (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    DiseaseName NVARCHAR(100) NOT NULL,
    Specialization NVARCHAR(100) NOT NULL,
    Urgency NVARCHAR(20) DEFAULT 'routine'
);

INSERT INTO DiseaseSpecialization (DiseaseName, Specialization, Urgency) VALUES
('Fungal infection','Dermatologist','routine'),
('Allergy','Allergist','routine'),
('GERD','Gastroenterologist','routine'),
('Chronic cholestasis','Gastroenterologist','urgent'),
('Drug Reaction','Allergist','urgent'),
('Peptic ulcer disease','Gastroenterologist','routine'),
('AIDS','Infectious Disease Specialist','urgent'),
('Diabetes','Endocrinologist','routine'),
('Gastroenteritis','Gastroenterologist','routine'),
('Bronchial Asthma','Pulmonologist','urgent'),
('Hypertension','Cardiologist','urgent'),
('Migraine','Neurologist','routine'),
('Cervical spondylosis','Orthopedist','routine'),
('Paralysis (brain hemorrhage)','Neurologist','emergency'),
('Jaundice','Hepatologist','urgent'),
('Malaria','Infectious Disease Specialist','urgent'),
('Chicken pox','Dermatologist','routine'),
('Dengue','Infectious Disease Specialist','urgent'),
('Typhoid','Infectious Disease Specialist','urgent'),
('Hepatitis A','Hepatologist','urgent'),
('Hepatitis B','Hepatologist','urgent'),
('Hepatitis C','Hepatologist','urgent'),
('Hepatitis D','Hepatologist','urgent'),
('Hepatitis E','Hepatologist','urgent'),
('Alcoholic hepatitis','Hepatologist','urgent'),
('Tuberculosis','Pulmonologist','urgent'),
('Common Cold','General Physician','routine'),
('Pneumonia','Pulmonologist','urgent'),
('Dimorphic hemmorhoids','Gastroenterologist','routine'),
('Heart attack','Cardiologist','emergency'),
('Varicose veins','Vascular Surgeon','routine'),
('Hypothyroidism','Endocrinologist','routine'),
('Hyperthyroidism','Endocrinologist','routine'),
('Hypoglycemia','Endocrinologist','urgent'),
('Osteoarthritis','Orthopedist','routine'),
('Arthritis','Rheumatologist','routine'),
('Paroxysmal Positional Vertigo','ENT Specialist','routine'),
('Acne','Dermatologist','routine'),
('Urinary tract infection','Urologist','routine'),
('Psoriasis','Dermatologist','routine'),
('Impetigo','Dermatologist','routine');